# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'postillon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for postillon
  pod 'Firebase/Core', '~> 5.9.0'

  pod 'Firebase/AdMob', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'

  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  
  target 'postillon-tvOSTests' do
    inherit! :search_paths

    # pod 'RNSVG', :path => '../node_modules/react-native-svg'

    # pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  end

  target 'postillonTests' do
    inherit! :search_paths
  end

end

