export const ANALYTICS_EVENT_ARTICLE_OPENED = 'article_opened';
export const ANALYTICS_EVENT_ARTICLE_SAVED = 'article_saved';
export const ANALYTICS_EVENT_ARTICLE_SAVED_TEXT_ONLY = 'article_saved_text_only';
export const ANALYTICS_EVENT_ARTICLE_REMOVED = 'article_removed';
export const ANALYTICS_EVENT_ARTICLE_SEARCHED = 'article_searched';


export default {
    ANALYTICS_EVENT_ARTICLE_OPENED,
    ANALYTICS_EVENT_ARTICLE_SAVED,
    ANALYTICS_EVENT_ARTICLE_SAVED_TEXT_ONLY,
    ANALYTICS_EVENT_ARTICLE_REMOVED,
    ANALYTICS_EVENT_ARTICLE_SEARCHED,
}
